# Generated by Django 6.0.7 on 2026-07-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='creat_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
